name: flutter_car_live
description: Flutter 脚手架
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+71

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  connectivity: ^3.0.3

  encrypt: ^5.0.0

  animated_text_kit: ^4.2.1

  flutter_swiper_null_safety: ^1.0.2
  sensors_plus: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  flutter_slidable: ^0.5.7
  # cached_network_image: ^3.0.0
  # 权限请求
  permission_handler: 8.1.4+1

  signature: ^4.1.1

  # App版本信息
  package_info: ^2.0.2
  # 用来加载网络数据
  dio: ^4.0.4
  # WebView
  webview_flutter: ^1.0.7

  # 偏好设置
  shared_preferences: ^2.0.7
  # Material motion 规范的预构建动画
  animations: ^2.0.2
  # 饼图
  # flutter_echart: ^1.0.2
    #path: /Volumes/code/ico/Desktop/code/flutter_app/flutter_echart

  # 路径获取
  path_provider: ^2.0.2
  # 视频播放
  # video_player: ^1.0.1
  # toast 消息提示小弹框
  fluttertoast: ^8.0.8
  # picker选择器
  flutter_picker: ^2.0.2
  # 拍照/相册
  image_picker: ^0.8.4+1
  # 扫码
  qrscan: ^0.3.2
  # 图片预览
  photo_view: ^0.13.0
  flutter_svg: ^0.21.0-nullsafety.0
  # 上拉加载下拉刷新
  flutter_easyrefresh: ^2.2.1
  # 事件总线
  # event_bus: ^2.0.0
  # easyloading弹窗后还可以点击页面元素,这明显不符合使用场景
  flutter_easyloading: ^3.0.3
  provider: ^6.0.1
  future_progress_dialog: ^0.2.0
  # 震动
  flutter_vibrate: ^1.3.0
  # 定位// 无google服务
  # location: ^4.3.0
  # 播放音频
  audioplayers: ^0.20.1
  # 下载更新
  r_upgrade: ^0.3.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json转dart类, dartsdk版本低安装不成功,需要dart sdk>2.14的版本
  # json_model: ^1.0.0
  # json_serializable: ^5.0.0
  json2dart_safe: ^1.0.8+9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/common/
    - assets/images/owner/
    - assets/images/card/
    - assets/video/sound1.wav
    - assets/video/tts.mp3

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/iconfont/iconfont.ttf